theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap

title: bert
description: a CLI benchmarking tool that allows you to collect performance stats for any number of commands, label and save them in several file formats for further analysis and display
